### ISSUE TITLE
More banks needed to be added

### ISSUE THREAD

**Issue by gked** [YunoHost-Apps/kresus_ynh#105]
Hi All,
Are there any plans to add support for more banks?
What is the process to onboard a new bank into kresus?

thanks,

**Comment by nicofrand** [comment]
Hi!

Kresus uses woob to retrieve data from the banks website, so the easiest 
way is to add a module (in python) to woob, which will then be available in 
Kresus.

**Comment by bnjbvr** [comment]
Hi! To build a bit upon this answer: we need a programmatic way to retrieve the bank's information, namely bank account info as well as transactions' information. French banks don't easily give this information back, so we're relying on a solution built on scrapers built on [woob](https://woob.tech/). If you have other ways to integrate with your local bank APIs, we could make a plugin to use that instead!

(A note: in Europe there's the PSD2 directive that in theory should give us access to this info, unfortunately there's some serious legal gatekeeping that prevents free software and non-corporate entities (such as: individuals) from getting access to those APIs)

**Comment by nicofrand** [comment]
Closing this issue as this is an upstream's issue, thanks.
