### ISSUE TITLE
libopenjp2.so.7 - Cannot open shared object file - No such file or directory

### ISSUE THREAD

**Issue by A-Nicoladie** [YunoHost-Apps/kresus_ynh#112]
### Describe the bug

On a fresh install (YH and Kresus), when I try to setup a new account I get this message:  
> Votre banque utilise un module non supporté par Kresus (et Woob) ou il manque une dépendance. Essayez de mettre à jour Woob ou contactez un mainteneur.

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH | Through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: Kresus 0.17.4

### Steps to reproduce

   1. Add a new account
   2. Select my bank
   3. Input my ID and password
   4. Click add button

### Logs

[https://paste.yunohost.org/utedutadah](https://paste.yunohost.org/utedutadah)  

### Fix

In command line interface, run the following command:  
`sudo apt install libopenjp2-7`

**Comment by nicofrand** [comment]
Thanks for reporting! I created a merge request for this.
