### ISSUE TITLE
[Testing] Error during upgrade to testing branch version 0.18.1

### ISSUE THREAD

**Issue by raphraph** [YunoHost-Apps/kresus_ynh#125]
### Bug description

An error occurred during the upgrade from the last stable version (0.17.4~ynh2) to testing branch version 0.18.1 and I don't understand the error.

### Context

- Hardware: RaspberryPI 3
- YunoHost version: 4.3.6.3 (stable)
- I have access to my server: *through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *NO*
- Using, or trying to install package version/branch: *0.18.1~ynh1*
- If upgrading, current package version: *0.17.4\~ynh2 >> 0.18.1\~ynh1*

**EDIT:** I just realized that I made the upgrade as the **root** user and not as the **admin** user... I don't know if this can have an impact.

### Steps to reproduce

```sh
sudo yunohost app upgrade kresus -u https://github.com/YunoHost-Apps/kresus_ynh/tree/testing
```

### Expected behavior

No error...

### Logs

https://paste.yunohost.org/quzilamuxo

**Comment by raphraph** [comment]
FYI I tried removing (purging) the app and reinstalling from the testing branch and ran into the same error (this time I was correctly logged in as the admin user.

**Comment by raphraph** [comment]
I saw the last commits so I tried again installing the testing branch and this time it worked fine ! :+1:

**Comment by nicofrand** [comment]
Thanks a lot for the ticket and tests!
