### ISSUE TITLE
Systemd triggers "Failed at step SECUREBITS spawning"

### ISSUE THREAD

**Issue by fxleroy** [YunoHost-Apps/kresus_ynh#130]
This is the same bug than #127 

### Describe the bug

Kresus does not work anymore since 0.18.1~ynh4

### Context
Hardware: raspberry 
YunoHost version: 10 stable
I have access to my server: at home with ssh, webadmin 
Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
Using, or trying to install package version/branch: master
If upgrading, current package version: from 0.17.4.ynh2 to 0.18.1.ynh4

### Steps to reproduce

At the end of the upgrade process, the Kresus service can't start. To access my data, I have to launch Kresus manually : /var/www/kresus/bin/kresus.js --config /var/www/kresus/config.ini

### Expected behavior

The Kresus service is working

### Logs
Extract from "journalctl -xe"

-- The job identifier is 36474 and the job result is failed.
Jun 28 19:49:51 syno.leroychezmoi.fr sudo[2178]:    admin : TTY=pts/0 ; PWD=/home/admin ; USER=root ; COMMAND=/usr/sbin/service kresus resta
Jun 28 19:49:51 syno.leroychezmoi.fr sudo[2178]: pam_unix(sudo:session): session opened for user root by admin(uid=0)
Jun 28 19:49:51 syno.leroychezmoi.fr systemd[1]: kresus.service: Start request repeated too quickly.
Jun 28 19:49:51 syno.leroychezmoi.fr systemd[1]: kresus.service: Failed with result 'exit-code'.
-- Subject: Unit failed

### Tests made 
Like the #127 I try to comment the followings lines in the conf/systemd.service file : 
#ProtectSystem=strict 
#SecureBits=noroot-locked
#SystemCallArchitectures=native
#SystemCallFilter=@system-service
#SystemCallErrorNumber=EPERM

This seems to work, but after this change, I got the "https://framagit.org/kresusapp/kresus/-/issues/1173" error :-D

**Comment by nicofrand** [comment]
Which version of Yunohost are you using?

And I don't understand why you say "like the #127": the systemd likes you commented are not mentioned in #127?

**Comment by fxleroy** [comment]
> Which version of Yunohost are you using?
> 
> And I don't understand why you say "like the #127": the systemd likes you commented are not mentioned in #127?

Sorry, I meant it was the same kind of error in the same place.



> Can you give more journalctl logs please?

Jun 28 21:22:16 domaine.fr systemd[1]: Started kresus.
Jun 28 21:22:16 domaine.fr systemd[29522]: kresus.service: Failed to set process secure bits: Operation not permitted
Jun 28 21:22:16 domaine.fr systemd[29522]: kresus.service: Failed at step SECUREBITS spawning /var/www/kresus/bin/kresus.js: Opera
Jun 28 21:22:16 domaine.fr systemd[1]: kresus.service: Main process exited, code=exited, status=213/SECUREBITS
Jun 28 21:22:16 domaine.fr systemd[1]: kresus.service: Failed with result 'exit-code'.
Jun 28 21:22:16 domaine.fr systemd[1]: kresus.service: Service RestartSec=100ms expired, scheduling restart.
Jun 28 21:22:16 domaine.fr systemd[1]: kresus.service: Scheduled restart job, restart counter is at 5.
Jun 28 21:22:16 domaine.fr systemd[1]: Stopped kresus.
Jun 28 21:22:16 domaine.fr systemd[1]: kresus.service: Start request repeated too quickly.
Jun 28 21:22:16 domaine.fr systemd[1]: kresus.service: Failed with result 'exit-code'.
Jun 28 21:22:16 domaine.fr systemd[1]: Failed to start kresus.

**Comment by nicofrand** [comment]
OK thanks. And which version of Yunohost are you using?

**Comment by nicofrand** [comment]
Thanks.

The first one is already commented: https://github.com/YunoHost-Apps/kresus_ynh/blob/master/conf/systemd.service#L43
For the second I'd like to reproduce the issue before changing anything :/.

**Comment by nicofrand** [comment]
I think that's linked to Raspberry/ARM only…
Coudl you test something for me please?

1. Uncomment ``
2. Replace `SystemCallFilter=@system-service` with `SystemCallFilter=~@clock @debug @module @mount @obsolete @reboot @setuid @swap`

**Comment by fxleroy** [comment]
It's in the same line ? Or every "@" is on separate line ?

In the first case, it's working, but I don't see more debug logs.

**Comment by nicofrand** [comment]
Yes, on the same line! I'll fix it then, thanks
