### ISSUE TITLE
node-pre-gyp install --fallback-to-build error during installation 

### ISSUE THREAD

**Issue by GTHeyyy** [YunoHost-Apps/kresus_ynh#144]
Hi!

I try to install Kresus on my Yunohost server.
Config : 
Yunohost 11.0.10.2
RPI4

The log : https://paste.yunohost.org/raw/uxumozijab

Thank's by advance.

**Comment by nicofrand** [comment]
Hi,

Does it happen each time you try?

**Comment by GTHeyyy** [comment]
Yes I tried several times. Another user on the chat tried with the same result

**Comment by nicofrand** [comment]
OK, that seems to come from this issue: https://github.com/TryGhost/node-sqlite3/issues/1103.

Can you give me the output of `which python` and `python --version` please?

**Comment by GTHeyyy** [comment]
Hi!
`admin@local:~ $ which python
/usr/bin/python`
`admin@local:~ $ python --version
Python 3.9.2`

Thank's for your help

**Comment by nicofrand** [comment]
OK, so it seems to be fixed in node-sqlite3  version 5.0.3 (https://github.com/TryGhost/node-sqlite3/issues/1554#issuecomment-1098143970) but the version required by Kresus (currently) is 5.0.2 https://framagit.org/kresusapp/kresus/-/blob/builds/package.json#L87.

I'll see if we can release a 0.18.2 of Kresus to target 5.0.3+.

**Comment by nicofrand** [comment]
Hm, now that I think of it, sqlite3 is a dev dependency and should not be installed.

**Comment by nicofrand** [comment]
OK, got it: https://github.com/YunoHost-Apps/kresus_ynh/commit/95a61a949d85a726365a452cceb58a9c9d7fa2bc we still install all dependencies. I'll try and fix that.

**Comment by nicofrand** [comment]
I shipped a new `0.18.1~ynh9` version that should fix it. It should be available in a few hours.

**Comment by GTHeyyy** [comment]
All right! It works perfectly now! Thanks a lot
