### ISSUE TITLE
[multi-instance] : nginx conf for new instance and @ directives

### ISSUE THREAD

**Issue by bidroidk** [YunoHost-Apps/kresus_ynh#147]
Hi,

I use two instances of Kresus and issue appears at the second installation.

I used admin panel to install Kresus.

I changed the original "libellé" and url which is by default "kresus".
I used "picsou" instead of the default.

The issue appears in the nginx configuration file : `/etc/nginx/conf.d/MY_DOMAIN/kresus__2.conf `where directives `@xxxxx` stays with `@kresus` instead of the name of the url I asked.

I made the replacement by myself and it worked : 

```
--- /root/kresus__2.conf	2022-11-27 18:58:22.892938263 +0100
+++ kresus__2.conf	2022-11-27 19:00:59.982965186 +0100
@@ -2,7 +2,7 @@
 location /picsou/ {
 
   alias /var/www/kresus__2/build/client/;
-  try_files $uri $uri/index.html @kresus;
+  try_files $uri $uri/index.html @picsou;
 
   # Include SSOWAT user panel.
   include conf.d/yunohost_panel.conf.inc;
@@ -11,10 +11,10 @@
 location ~ /picsou/\.(css|js|png|jpe?g|svg|eot|woff2?)$ {
   more_set_headers 'Cache-Control: max-age=2592000, must-revalidate, public';
   gzip_types text/plain text/css application/javascript text/javascript;
-  try_files $uri $uri/index.html @kresus;
+  try_files $uri $uri/index.html @picsou;
 }
 
-location @kresus {
+location @picsou {
   client_max_body_size  8M;
   send_timeout          600;
   proxy_connect_timeout 600;
```

I do not know if this a bug or not and sorry for the noise if not.

# Context
- Hardware: old sff computer at home
- YunoHost version: 11.0.10.2
- I have access to my server: Through SSH and through the webadmin and direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

Throught the webadmin panel, just install an new instance of kresus and change libellé and url.
I guess the root cause is url and not libellé of course

### Expected behavior

Nginx configuration for the new instance with right value for nginx "@xxxxx" directives.

### Logs

No logs but if you tell me where to find logs I can give them to you

Many thanks

regards

**Comment by nicofrand** [comment]
Should be fixed in https://github.com/YunoHost-Apps/kresus_ynh/pull/148
