### ISSUE TITLE
Boursorama unsupported or Woob out

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/kresus_ynh#157]
Kresus: 0.19.2~ynh2
YunoHost 11.1.18 (stable)
In the admin page: Votre version de Woob courante est la 3.4.
Since 08 of april, Boursorama is not updated anymore, with the following message:
`Votre banque utilise un module non supporté par Kresus (et Woob) ou il manque une dépendance. Essayez de mettre à jour Woob ou contactez un mainteneur.`

**Comment by nicofrand** [comment]
No update on the matter, closing this issue.
