### ISSUE TITLE
For ARM, Weboob requires some extra dependencies

### ISSUE THREAD

**Issue by ZeHiro** [YunoHost-Apps/kresus_ynh#17]
Some python modules required by weboob are not distributed for ARM architectures. They need to be compiled and need some extra dev dependancies:
`libxslt-dev libjpeg-dev libxml2-dev`
I tested on raspberry pi 2

As this does not affect the othre 'normal' architectures, a test on the arch using the result of the command  `arch` could be interesting.

**Comment by Jibec** [comment]
can you please try the testing branch?

```
sudo yunohost app install https://github.com/YunoHost-Apps/kresus_ynh/tree/testing --verbose
or
sudo yunohost app upgrade kresus -u https://github.com/YunoHost-Apps/kresus_ynh/tree/testing --verbose
```

**Comment by ZeHiro** [comment]
I installed it, and it worked. It took only 900s (15min), compared to previous installs which was 3hours due to compiling \o/. I think however that, the developpement dependencies (`libxslt-dev libjpeg-dev libxml2-dev`) are not anymore useful as we allow the virtualenv to use the global ackages like `python-lxml` and `python-pillow`.

**Comment by Jibec** [comment]
I removed the dev dependencies, can you please test again and confirm it 
works?
(same command as earlier)

**Comment by Jibec** [comment]
fixed by https://github.com/YunoHost-Apps/kresus_ynh/pull/21
