### ISSUE TITLE
ERREUR en mise à jour Kresus

### ISSUE THREAD

**Issue by JacquelinDV** [YunoHost-Apps/kresus_ynh#181]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

Je n'arrive pas à mettre à jour Kresus

### Context

- Raspberry pi 3BHardware: Raspberry pi 3B
- YunoHost version: 11.2.9.1
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
 -trying to install package version/branch: kresus 
env:
  YNH_APP_ACTION: upgrade
  YNH_APP_BASEDIR: /var/cache/yunohost/app_tmp_work_dirs/app_t6zzvrld
  YNH_APP_CURRENT_VERSION: 0.20.1~ynh1
  YNH_APP_ID: kresus
  YNH_APP_INSTANCE_NAME: kresus
  YNH_APP_INSTANCE_NUMBER: '1'
  YNH_APP_MANIFEST_VERSION: 0.20.1~ynh2
  YNH_APP_PACKAGING_FORMAT: '2.0'
  YNH_APP_UPGRADE_TYPE: UPGRADE_PACKAGE
  YNH_ARCH: arm64
  YNH_DEBIAN_VERSION: bullseye
error: "Une erreur s'est produite durant l'ex\xE9cution du script de mise \xE0 niveau\
  \ de l'application"
interface: api
operation: app_upgrade
parent: null
related_to:
- - app
  - kresus
started_at: 2024-01-16 16:43:28.297512
success: false
yunohost_version: 11.2.9.1
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Logs
https://paste.yunohost.org/raw/ahogumapip

La ligne d'erreur sermble être : 
2024-01-16 17:57:10,999: DEBUG - info There appears to be trouble with your network connection. Retrying...
2024-01-16 17:57:35,796: DEBUG - info There appears to be trouble with your network connection. Retrying...
2024-01-16 17:57:44,290: DEBUG - info There appears to be trouble with your network connection. Retrying...
2024-01-16 17:58:09,192: DEBUG - info There appears to be trouble with your network connection. Retrying...
2024-01-16 17:58:17,465: DEBUG - info There appears to be trouble with your network connection. Retrying...
2024-01-16 17:58:42,504: DEBUG - info There appears to be trouble with your network connection. Retrying...
2024-01-16 17:58:50,700: DEBUG - info There appears to be trouble with your network connection. Retrying...
2024-01-16 17:59:15,896: DEBUG - info There appears to be trouble with your network connection. Retrying...
2024-01-16 17:59:30,103: DEBUG - error An unexpected error occurred: "https://registry.yarnpkg.com/date-fns/-/date-fns-2.29.3.tgz: ESOCKETTIMEDOUT".
2024-01-16 17:59:30,105: DEBUG - info If you think this is a bug, please open a bug report with the information provided in "/var/www/kresus/yarn-error.log".

**Comment by nicofrand** [comment]
Hi,

> 2024-01-16 17:59:30,103: DEBUG - error An unexpected error occurred: "https://registry.yarnpkg.com/date-fns/-/date-fns-2.29.3.tgz: ESOCKETTIMEDOUT".

There was either an issue with the yarn registry or with your connection. Please try again.

**Comment by nicofrand** [comment]
Quelle connectivité a le raspberry ? Filaire, wifi ? Il y a un firewall derrière ?

**Comment by JacquelinDV** [comment]
Connection Fuilaire avec une ip fixe et un vpn.
Utilisation du firewall de YunoHost

**Comment by nicofrand** [comment]
Quels sont les retours de :

```
curl "https://registry.yarnpkg.com/date-fns/-/date-fns-2.29.3.tgz" -o /tmp/test-ipv4.tgz -4 -v
```

et 

```
curl "https://registry.yarnpkg.com/date-fns/-/date-fns-2.29.3.tgz" -o /tmp/test-ipv6.tgz -6 -v
```

**Comment by JacquelinDV** [comment]
Voilà lers retours
____________________________
**curl "https://registry.yarnpkg.com/date-fns/-/date-fns-2.29.3.tgz" -o /tmp/test-ipv4.tgz -4 -v**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.16.27.34:443...
* Connected to registry.yarnpkg.com (104.16.27.34) port 443 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [104 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2298 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [115 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=registry.yarnpkg.com
*  start date: Apr  6 00:00:00 2023 GMT
*  expire date: Apr  5 23:59:59 2024 GMT
*  subjectAltName: host "registry.yarnpkg.com" matched cert's "registry.yarnpkg.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x55b46aa040)
} [5 bytes data]
> GET /date-fns/-/date-fns-2.29.3.tgz HTTP/2
> Host: registry.yarnpkg.com
> user-agent: curl/7.74.0
> accept: */*
>
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
} [5 bytes data]
< HTTP/2 200
< date: Thu, 01 Feb 2024 19:54:15 GMT
< content-type: application/octet-stream
< content-length: 729338
< cf-ray: 84ecbec4c894d3bb-CDG
< cf-cache-status: HIT
< accept-ranges: bytes
< access-control-allow-origin: *
< age: 1206961
< cache-control: public, immutable, max-age=31557600
< etag: "d0b281d07e151f83b1a05f1df0ec5c0a"
< last-modified: Tue, 13 Sep 2022 12:36:13 GMT
< vary: Accept-Encoding
< server: cloudflare
<
{ [5 bytes data]
100  712k  100  712k    0     0  1292k      0 --:--:-- --:--:-- --:--:-- 1292k
* Connection #0 to host registry.yarnpkg.com left intact
___________________________________________________________
**curl "https://registry.yarnpkg.com/date-fns/-/date-fns-2.29.3.tgz" -o /tmp/test-ipv6.tgz -6 -v**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 2606:4700::6810:323:443...
* Connected to registry.yarnpkg.com (2606:4700::6810:323) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [104 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2298 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [115 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=registry.yarnpkg.com
*  start date: Apr  6 00:00:00 2023 GMT
*  expire date: Apr  5 23:59:59 2024 GMT
*  subjectAltName: host "registry.yarnpkg.com" matched cert's "registry.yarnpkg.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x5580e58040)
} [5 bytes data]
> GET /date-fns/-/date-fns-2.29.3.tgz HTTP/2
> Host: registry.yarnpkg.com
> user-agent: curl/7.74.0
> accept: */*
>
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
} [5 bytes data]
< HTTP/2 200
< date: Thu, 01 Feb 2024 19:56:02 GMT
< content-type: application/octet-stream
< content-length: 729338
< cf-ray: 84ecc16618e10350-CDG
< cf-cache-status: HIT
< accept-ranges: bytes
< access-control-allow-origin: *
< age: 1791553
< cache-control: public, immutable, max-age=31557600
< etag: "d0b281d07e151f83b1a05f1df0ec5c0a"
< last-modified: Tue, 13 Sep 2022 12:36:13 GMT
< vary: Accept-Encoding
< server: cloudflare
<
{ [5 bytes data]
100  712k  100  712k    0     0  1380k      0 --:--:-- --:--:-- --:--:-- 1380k
* Connection #0 to host registry.yarnpkg.com left intact

**Comment by nicofrand** [comment]
Peux-tu essayer la branche https://github.com/YunoHost-Apps/kresus_ynh/tree/fixYarnSlowDevices stp ?

**Comment by JacquelinDV** [comment]
Comment faire? 
J'ai un accès SSH à la machine YunoHost.

**Comment by nicofrand** [comment]
Lancer quelque chose comme `sudo yunohost app upgrade kresus -u https://github.com/YunoHost-Apps/kresus_ynh/tree/fixYarnSlowDevices`

Voir https://forum.yunohost.org/t/testing-branches-for-apps/3470

**Comment by JacquelinDV** [comment]
Merci beaucoup, l'update a bien étéc effectué  sans etrreur! Avec la commande bproposée.
