### ISSUE TITLE
Add support for multiple users

### ISSUE THREAD

**Issue by bnjbvr** [YunoHost-Apps/kresus_ynh#22]
Some work is needed on the Kresus side (handle multiple users), but there's going to be some bits needed for the integration in YNH too.

**Comment by Jibec** [comment]
thank you for working on this Benjamin, but I would rather keep here only issues on things I (or other) can fix inside the package. This is an interesting feature to be added upstream, and as such, should be tracked upstream.

you're welcome to re-open this issue if you wish to continue the discussion

**Comment by bnjbvr** [comment]
Oh, so there's nothing at all to do on the package's side? If so, that's great! I opened an issue because I thought differently.
