### ISSUE TITLE
Impossible to add a bank

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/kresus_ynh#28]
I just installed Kresus in YunoHost and I am not able to connect any bank.
I tried my bank and a few random (with random login/password).
Each time I have the following message : 

> Votre banque utilise un module non supporté par Kresus (et Weboob) ou il manque une dépendance. Essayez de mettre à jour Weboob ou contactez un mainteneur.

I have no idea on how to update Weboob, so I contact a maintainer :slightly_smiling_face:

**Comment by Jibec** [comment]
hello, thanks for taking the time to report your issue

What's your server platform? x86_64 or arm?
Did it ever worked before?
Have you tried with the "fake banks"?

Do you know how to connect in ssh to your machine and real logs? You should be able to see the log with `sudo journalctl -u kresus`.
I now realize it could be a good thing to make the log available in the admin interface...

**Comment by ZeHiro** [comment]
I have opened an issue to improve the way Kresus warns there is a problem, this will be adressed in next version of Kresus: https://framagit.org/kresusapp/kresus/issues/829

**Comment by supermamie** [comment]
@Jibec I'm on a x64 computer.
It never worked before as I just installed kresus.
I just tried a fake bank and it works just fine.
I see nothing wrong in the log, every line is in state "succeeded"

@ZeHiro That may be the source of my problem :slightly_smiling_face: 
Now that I have a fake bank, I was able to access the "update weboob" button, which fails (may be because of this too)

> Error when updating weboob: Exception when updating weboob: 'DummyProgress' object has no attribute 'error'.
Traceback (most recent call last):
  File "/var/www/kresus/build/server/weboob/main.py", line 715, in main
    weboob_connector.update()
  File "/var/www/kresus/build/server/weboob/main.py", line 315, in update
    self.weboob.update(progress=DummyProgress())
  File "/var/www/kresus/venv/local/lib/python2.7/site-packages/weboob/core/ouiboube.py", line 394, in update
    self.repositories.update(progress)
  File "/var/www/kresus/venv/local/lib/python2.7/site-packages/weboob/core/repositories.py", line 649, in update
    self.update_repositories(progress)
  File "/var/www/kresus/venv/local/lib/python2.7/site-packages/weboob/core/repositories.py", line 619, in update_repositories
    progress.error('Unable to load repository: %s' % e)
AttributeError: 'DummyProgress' object has no attribute 'error'

**Comment by ZeHiro** [comment]
@supermamie you hit another bug :p

**Comment by ZeHiro** [comment]
@supermamie can you try again, things seem to be back on.

**Comment by supermamie** [comment]
New error now :

> Unknown error: .
Erreur inconnue de Kresus : essayez de mettre à jour Weboob, et si cela ne règle pas votre problème, merci de signaler l'erreur aux auteurs de Kresus.
> 
> Veuillez vous référer à la console développeurs pour plus d'informations.

No error in `sudo journalctl -u kresus`
But there are some things in the logs available in kresus (the webapp)

[Paste of the log](https://text.mamieserv.fr/?171a7a5143616cfc#/HlX9LW9DNtzn4t7LbgCUYhx0q/1Cq3HC/ynEBRpOGU=)

**Comment by ZeHiro** [comment]
This time, the problem is on weboob side. Looks like the module is half finished... The only option is to wait, and try regularly... Do you have another bank for which you could try Kresus ?

**Comment by supermamie** [comment]
I tried with another bank, and it works, so I can close this issue.

Thank you for your help.

I'll try again in a few days with my main bank.

**Comment by Jibec** [comment]
please delete the log you shared, it contains personal data (depending on where you set your limits), at least your bank id ain't to be known by anyone. Less private is the list of your accounts.

**Comment by supermamie** [comment]
I modified the bank id, the one in the log is false, but thanks :slightly_smiling_face:

**Comment by ZeHiro** [comment]
@supermamie the module societegeneral was upgraded yesterday and should just work fine

**Comment by supermamie** [comment]
@ZeHiro Thanks a lot, I tried yesterday afternoon without success, but now it works.
