### ISSUE TITLE
Kresus has been updated to 0.14.0

### ISSUE THREAD

**Issue by bnjbvr** [YunoHost-Apps/kresus_ynh#29]
Hi there! Kresus has just been updated ([French blog post](https://kresus.org/blog/kresus-version-0-14-0.html)). I think a version bump is necessary, and it'd be nice if the YNH script could generate a `salt` option in the `config.ini` file (16+ random characters) to make it possible to export encrypted backups. Thanks and keep up the good work! :+1:

**Comment by Jibec** [comment]
Well, i normally dislike messages like this one (ask to support a release that is out since a few hours/days), but I have to say I'm happy :)
It's coming from the upstream team, there is a full article on the matter and includes a little help to make the upgrade smoother.
<3
