### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by El-Gavy** [YunoHost-Apps/kresus_ynh#31]
Hi,

I tried installing the app but it was not successful.

Here is the log of my try : 

> 2019-03-01 10:45:52,475: WARNING - debconf: unable to initialize frontend: Dialog
> 2019-03-01 10:45:52,477: WARNING - debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
> 2019-03-01 10:45:52,477: WARNING - debconf: falling back to frontend: Readline
> 2019-03-01 10:45:52,477: WARNING - debconf: unable to initialize frontend: Readline
> 2019-03-01 10:45:52,478: WARNING - debconf: (This frontend requires a controlling tty.)
> 2019-03-01 10:45:52,478: WARNING - debconf: falling back to frontend: Teletype
> 2019-03-01 10:45:52,478: WARNING - dpkg-preconfigure: unable to re-open stdin:
> 2019-03-01 10:46:01,910: WARNING - Installation of N - Node.js version management
> 2019-03-01 10:46:05,622: WARNING - 
>                                                                            0.1%
>                                                                            0.3%
> #                                                                          1.4%
> ###                                                                        5.2%
> #######                                                                   10.7%
> ##############                                                            20.3%
> #####################                                                     30.5%
> #################################                                         46.9%
> ###########################################                               60.8%
> ####################################################                      72.4%
> #############################################################             85.8%
> ######################################################################    98.5%
> ######################################################################## 100.0%
> 2019-03-01 10:46:06,626: WARNING - ./install: line 105: virtualenv: command not found
> 2019-03-01 10:46:06,626: WARNING - !!
> 2019-03-01 10:46:06,627: WARNING -   kresus's script has encountered an error. Its execution was cancelled.
> 2019-03-01 10:46:06,627: WARNING - !!
> 2019-03-01 10:46:06,627: WARNING -

**Comment by Jibec** [comment]
hello, thanks for opening this issue, I just pushed a new version of kresus. I am unsure it will change anything, but please try.
Your log file looks weird, is your YunoHost server up to date? What is your server version and the architecture?

**Comment by El-Gavy** [comment]
Hello, sorry for the delay, i'm trying to update all my YunoHost and then i'll try again !

**Comment by Jibec** [comment]
kind remember: can you confirm it works?

**Comment by El-Gavy** [comment]
Hi,

I did all the updates and migrations of YunoHost before trying again. Hélas, didn't work again.

Here is the full log : https://paste.yunohost.org/raw/rowuwowize

**Comment by batal1** [comment]
Hi,

It seems I have the same issue on my Lime2 box.
Please see the log below:
2019-05-15 22:45:59,854: DEBUG - + VALUE=8
2019-05-15 22:45:59,856: DEBUG - + python -
2019-05-15 22:46:00,664: DEBUG - + ynh_cron_upgrade_node
2019-05-15 22:46:00,666: DEBUG - + cat
2019-05-15 22:46:00,669: DEBUG - + chmod +x /opt/node_n/node_update.sh
2019-05-15 22:46:00,671: DEBUG - + cat
2019-05-15 22:46:00,673: DEBUG - + chmod +x /etc/cron.daily/node_update
2019-05-15 22:46:00,676: DEBUG - + ynh_use_nodejs
2019-05-15 22:46:00,678: DEBUG - ++ ynh_app_setting_get --app=kresus --key=nodejs_version
2019-05-15 22:46:00,680: DEBUG - ++ local legacy_args=ak
2019-05-15 22:46:00,683: DEBUG - ++ args_array=([a]=app= [k]=key=)
2019-05-15 22:46:00,685: DEBUG - ++ declare -Ar args_array
2019-05-15 22:46:00,687: DEBUG - ++ local app
2019-05-15 22:46:00,690: DEBUG - ++ local key
2019-05-15 22:46:00,692: DEBUG - ++ ynh_handle_getopts_args --app=kresus --key=nodejs_version
2019-05-15 22:46:00,694: DEBUG - ++ set +x
2019-05-15 22:46:00,797: DEBUG - ++ ynh_app_setting get kresus nodejs_version
2019-05-15 22:46:00,799: DEBUG - ++ ACTION=get
2019-05-15 22:46:00,801: DEBUG - ++ APP=kresus
2019-05-15 22:46:00,803: DEBUG - ++ KEY=nodejs_version
2019-05-15 22:46:00,805: DEBUG - ++ VALUE=
2019-05-15 22:46:00,807: DEBUG - ++ python -
2019-05-15 22:46:01,585: DEBUG - + nodejs_version=8
2019-05-15 22:46:01,588: WARNING - ./install: ligne 107: virtualenv : commande introuvable
2019-05-15 22:46:01,591: DEBUG - + nodejs_use_version='echo "Deprecated command, should be removed"'
2019-05-15 22:46:01,607: WARNING - !!
2019-05-15 22:46:01,611: DEBUG - + nodejs_path=/opt/node_n/n/versions/node/8/bin
2019-05-15 22:46:01,624: WARNING -   kresus's script has encountered an error. Its execution was cancelled.
2019-05-15 22:46:01,629: DEBUG - + [[ :/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: == *\:\/\o\p\t\/\n\o\d\e\_\n\/\n\/\v\e\r\s\i\o\n\s\/\n\o\d\e\/\8\/\b\i\n* ]]
2019-05-15 22:46:01,631: WARNING - !!
2019-05-15 22:46:01,636: DEBUG - + PATH=/opt/node_n/n/versions/node/8/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2019-05-15 22:46:01,638: WARNING - 
2019-05-15 22:46:01,642: DEBUG - + virtualenv --system-site-packages /var/www/kresus/venv
2019-05-15 22:46:01,644: DEBUG - + ynh_exit_properly
2019-05-15 22:46:01,646: DEBUG - + local exit_code=127
2019-05-15 22:46:01,649: DEBUG - + '[' 127 -eq 0 ']'
2019-05-15 22:46:01,650: DEBUG - + trap '' EXIT
2019-05-15 22:46:01,652: DEBUG - + set +eu
2019-05-15 22:46:01,654: DEBUG - + echo -e '!!\n  kresus'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-05-15 22:46:01,656: DEBUG - + type -t ynh_clean_setup
2019-05-15 22:46:01,658: DEBUG - + ynh_die
2019-05-15 22:46:01,660: DEBUG - + local legacy_args=mc
2019-05-15 22:46:01,662: DEBUG - + args_array=([m]=message= [c]=ret_code=)
2019-05-15 22:46:01,664: DEBUG - + declare -Ar args_array
2019-05-15 22:46:01,666: DEBUG - + local message
2019-05-15 22:46:01,668: DEBUG - + local ret_code
2019-05-15 22:46:01,670: DEBUG - + ynh_handle_getopts_args
2019-05-15 22:46:01,672: DEBUG - + set +x
2019-05-15 22:46:01,674: DEBUG - + echo ''
2019-05-15 22:46:01,676: DEBUG - + exit 1

**Comment by nicofrand** [comment]
Hi there,

`virtualenv : commande introuvable` is the key. This should be available though: https://github.com/YunoHost-Apps/kresus_ynh/blob/master/scripts/install#L61.

Could you run:

```bash
apt-cache policy python-virtualenv
```

and 

```bash
which virtualenv
```

and give the result for each please?

**Comment by quentinDupont** [comment]
Also add the same type of error with virtualenv : https://paste.yunohost.org/raw/oyumisureh

And here is the result for the 1st command : 

`python-virtualenv:
  Installed: (none)
  Candidate: 15.1.0+ds-1
  Version table:
     15.1.0+ds-1 500
        500 http://debian.mirrors.ovh.net/debian stretch/main amd64 Packages`

and the 2nd command didn't retun anything

**Comment by nicofrand** [comment]
Can you run `apt install python-virtualenv` and try again?

**Comment by quentinDupont** [comment]
> Can you run `apt install python-virtualenv` and try again?

Fail again : https://paste.yunohost.org/raw/epuvolunax

**Comment by nicofrand** [comment]
Can you give the result of the apt install command please?

**Comment by quentinDupont** [comment]
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-virtualenv is already the newest version (15.1.0+ds-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded
```

**Comment by nicofrand** [comment]
Weird.

Can you give the results of: `find . -iname "virtualenv"` and `find /usr/ -iname "virtualenv" | grep bin` please?

**Comment by nicofrand** [comment]
Related issue: https://forum.yunohost.org/t/kresus-install-virtualenv-command-not-found/7909

**Comment by nicofrand** [comment]
Ah https://github.com/YunoHost-Apps/kresus_ynh/issues/35#issuecomment-512252996 might have found the issue: can you try to install `python3-virtualenv` and retry please?

**Comment by quentinDupont** [comment]
No result for the 2 commands before and after installing `python3-virtualenv`
And the install failed..
https://paste.yunohost.org/raw/uporuyajuy

**Comment by Jibec** [comment]
I think I should try to migrate the Kresus package to Python 3, this 
will hopefully solve this issue we don't know how to fix...

**Comment by GannonTdW** [comment]
I had the same problem, I posted a message on the yunohost forum and I completely forgot.

But @nicofrand  warned me that there was a problem open here and I started searching again.

And ... I think I found the solution : 
change `python-virtualenv` to `virtualenv`. 
it works for me. 
You can find my PR:  #36

**Comment by Jibec** [comment]
thank you @GannonTdW 
I produced this commit: https://github.com/YunoHost-Apps/kresus_ynh/commit/0d2aee061a07982bbb9c7357ef7425864d593ce5 , could you please test? Automated testing said it works fine.

**Comment by GannonTdW** [comment]
```
myuser@mysrv:~# yunohost log display 20190806-205641-app_install-kresus
description: Install 'kresus' application
log_path: /var/log/yunohost/categories/operation/20190806-205641-app_install-kresus.log
logs: 
  - 2019-08-06 20:59:48,107: DEBUG - Config: /var/www/kresus/config.ini
  - 2019-08-06 20:59:48,108: DEBUG - 
  - 2019-08-06 20:59:48,109: DEBUG - Please remember the default behavior of YunoHost when installing a new app is: everyone has access to the app.
  - 2019-08-06 20:59:48,110: DEBUG - This may be an issue for Kresus as it is a personnal tool. Please remember to edit access rights in the YunoHost web administration panel or using command line interface.
  - 2019-08-06 20:59:48,112: DEBUG - 
  - 2019-08-06 20:59:48,113: DEBUG - Note about config.ini: this package will regenerate the config file on upgrade.
  - 2019-08-06 20:59:48,114: DEBUG - If you changed it manually and upgrade Kresus, you'\''ll find a backup in /var/www/kresus.
  - 2019-08-06 20:59:48,115: DEBUG - 
  - 2019-08-06 20:59:48,116: DEBUG - Are you facing an issue, want to improve this app or say thank you?
  - 2019-08-06 20:59:48,117: DEBUG - Please open a new issue in this project: https://github.com/YunoHost-Apps/kresus_ynh
  - 2019-08-06 20:59:48,118: DEBUG - 
  - 2019-08-06 20:59:48,119: DEBUG - 
  - 2019-08-06 20:59:48,120: DEBUG - ---
  - 2019-08-06 20:59:48,121: DEBUG - Automatic diagnosis data from YunoHost
  - 2019-08-06 20:59:48,122: DEBUG - 
  - 2019-08-06 20:59:48,123: DEBUG - host: Debian 9.9
  - 2019-08-06 20:59:48,124: DEBUG - kernel: 4.9.0-9-amd64
  - 2019-08-06 20:59:48,125: DEBUG - packages:
  - 2019-08-06 20:59:48,127: DEBUG -   yunohost:
  - 2019-08-06 20:59:48,128: DEBUG -     repo: now
  - 2019-08-06 20:59:48,129: DEBUG -     version: 3.6.4.3
  - 2019-08-06 20:59:48,130: DEBUG -   yunohost-admin:
  - 2019-08-06 20:59:48,131: DEBUG -     repo: stable
  - 2019-08-06 20:59:48,142: DEBUG -     version: 3.6.4
  - 2019-08-06 20:59:48,144: DEBUG -   moulinette:
  - 2019-08-06 20:59:48,145: DEBUG -     repo: now
  - 2019-08-06 20:59:48,146: DEBUG -     version: 3.6.4
  - 2019-08-06 20:59:48,147: DEBUG -   ssowat:
  - 2019-08-06 20:59:48,149: DEBUG -     repo: stable
  - 2019-08-06 20:59:48,150: DEBUG -     version: 3.6.4
  - 2019-08-06 20:59:48,151: DEBUG - backports:
  - 2019-08-06 20:59:48,153: DEBUG - system:
  - 2019-08-06 20:59:48,154: DEBUG -   disks:
  - 2019-08-06 20:59:48,155: DEBUG -     sda1: Mounted on /boot, 486.8MiB (447.7MiB free)
  - 2019-08-06 20:59:48,156: DEBUG -     sda2: Mounted on /, 28.7GiB (25.3GiB free)
  - 2019-08-06 20:59:48,158: DEBUG -     sda3: Mounted on /home, 1.8TiB (1.8TiB free)
  - 2019-08-06 20:59:48,159: DEBUG -   memory:
  - 2019-08-06 20:59:48,160: DEBUG -     ram: 3.8GiB (2.9GiB free)
  - 2019-08-06 20:59:48,162: DEBUG -     swap: 511.0MiB (511.0MiB free)
  - 2019-08-06 20:59:48,163: DEBUG - nginx:
  - 2019-08-06 20:59:48,164: DEBUG -   - nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
  - 2019-08-06 20:59:48,166: DEBUG -   - nginx: configuration file /etc/nginx/nginx.conf test is successful'
  - 2019-08-06 20:59:48,468: DEBUG - + ynh_exit_properly
  - 2019-08-06 20:59:48,470: DEBUG - + local exit_code=0
  - 2019-08-06 20:59:48,472: DEBUG - + '[' 0 -eq 0 ']'
  - 2019-08-06 20:59:48,473: DEBUG - + exit 0
  - 2019-08-06 20:59:49,755: SUCCESS - The SSOwat configuration has been generated
  - 2019-08-06 20:59:49,757: SUCCESS - Installation complete
  - 2019-08-06 20:59:49,758: DEBUG - system hook folder not found for action 'post_app_install' in /usr/share/yunohost/hooks/
  - 2019-08-06 20:59:49,759: DEBUG - custom hook folder not found for action 'post_app_install' in /etc/yunohost/hooks.d/
metadata: 
  args: 
    app: https://github.com/YunoHost-Apps/kresus_ynh/tree/testing
    args: None
    force: False
    label: None
    no_remove_on_failure: False
  ended_at: 2019-08-06 20:59:49
  env: 
    YNH_APP_ARG_DOMAIN: mydomain.fr
    YNH_APP_ARG_PATH: /kresus
    YNH_APP_ID: kresus
    YNH_APP_INSTANCE_NAME: kresus
    YNH_APP_INSTANCE_NUMBER: 1
    YNH_CWD: /var/cache/yunohost/from_file/kresus_ynh-testing/scripts
    YNH_INTERFACE: cli
    YNH_STDINFO: /tmp/tmpH7Dal4/stdinfo
    YNH_STDRETURN: /tmp/tmp32E7Ks/stdreturn
  error: None
  operation: app_install
  related_to: 
    - app
    - kresus
  started_at: 2019-08-06 20:56:41
  success: True
metadata_path: /var/log/yunohost/categories/operation/20190806-205641-app_install-kresus.yml
name: 20190806-205641-app_install-kresus

```

Yes, it's works

**Comment by Jibec** [comment]
I feel like this issue is now totally fixed, please reopen if required
