### ISSUE TITLE
Failed to upgrade to 0.15.2 

### ISSUE THREAD

**Issue by Gofannon** [YunoHost-Apps/kresus_ynh#41]
Hello,

Upgrade failed on my server

**Log here:** https://paste.yunohost.org/pudenonilu.sql (Errors starts around lines 1550)

**YunoHost version**

    "host": "Debian 9.11",
    "kernel": "3.14.32-xxxx-grs-ipv6-64",
    "packages": {
        "yunohost": {
            "repo": "testing",
            "version": "3.7.0.4"
        },
        "yunohost-admin": {
            "repo": "testing",
            "version": "3.7.0.1"
        },
        "moulinette": {
            "repo": "testing",
            "version": "3.7.0"
        },
        "ssowat": {
            "repo": "testing",
            "version": "3.7.0.1"
        }
    },

**Comment by Jibec** [comment]
thanks for reporting this
what is the architecture?
did the restoration worked?
could you try to install a second kresus?

**Comment by Gofannon** [comment]
>  what is the architecture?

x86_64 (Kimsufi dedicated server)

> did the restoration worked?

Yes

> could you try to install a second kresus?

New installation failed too. See logs attached
1. [install new kresus.log](https://github.com/YunoHost-Apps/kresus_ynh/files/3950184/install.new.kresus.log)


2. [npm.log](https://github.com/YunoHost-Apps/kresus_ynh/files/3950183/npm.log)

Same failure after a reboot of the server and a new kresus install

Hope this helps. Feel free to ask for more details

**Comment by Jibec** [comment]
could you try again after installing these packages? `apt-get install pkg-config make g++`

**Comment by Jibec** [comment]
could you please provide /root/.npm/_logs/2019-12-09T09_15_23_648Z-debug.log?
this error with OVH and gyp is known: https://github.com/YunoHost-Apps/peertube_ynh/issues/36
but the fix is ugly and out of reach of casual user

**Comment by Jibec** [comment]
ok, forget my last comments, what is the list of application that you installed? `sudo yunohost app list --installed`

**Comment by Gofannon** [comment]
root@yunohost:~# sudo yunohost app list --installed | grep id | cut -d ':' -f2
agendav
airsonic
ampache
baikal
cheky
dokuwiki
dokuwiki__2
dokuwiki__3
freshrss
kanboard
kresus
nextcloud
rainloop
roundcube
shellinabox
transmission
wallabag2

**Comment by Jibec** [comment]
please try to upgrade to kresus 0.16

**Comment by nicofrand** [comment]
Closing this ticket due to the new version with 0.16. 
Please reopen an issue if needed.
