### ISSUE TITLE
NPM deprecated during 0.15 installation (but update works)

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/kresus_ynh#42]
For information, I got this message (a lot) during the installation of the 0.15 update:
_npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3._
Can we do someting about that?
thanks :)

**Comment by Jibec** [comment]
hello, thanks for your report, but this is an upstream issue you may report here: https://framagit.org/kresusapp/kresus
ping @ZeHiro

**Comment by klorydryk** [comment]
Ok, added [here](https://framagit.org/kresusapp/kresus/issues/914)
