### ISSUE TITLE
Bug in sender's email address when an alert email is sent

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/kresus_ynh#46]
When I receive an email alert from Kresus, everything is ok except the sender address which is `__APP__@__domain__`

Here is the source of one email : 
```
Return-Path: <SRS0=n+Qf=2R=__domain__=__APP__@blabla.fr>
Delivered-To: test@blabla.fr
Received: by wiphi.fr (Postfix, from userid 998)
	id 7A93F3E09D7; Fri, 27 Dec 2019 03:43:28 +0100 (CET)
Content-Type: text/plain; charset=utf-8
From: __APP__@__domain__
To: test@blabla.fr
Subject: Kresus - Alert on balance amount
Message-ID: <d2b98b51-dfb5-c058-4cda-6a5d88ed0a83@__domain__>
Content-Transfer-Encoding: quoted-printable
Date: Fri, 27 Dec 2019 02:43:28 +0000
MIME-Version: 1.0
[...]
```

**Comment by Jibec** [comment]
hello, sorry for late answer, which Kresus version do you have?
I can't reproduce this on my own server
please reopen if latest upgrade doesn't fix your issue

**Comment by SiM** [comment]
Hi,

The problem seems to have gone, maybe after upgrading following the 3rd January commits.
