### ISSUE TITLE
Install the pdfminer module by default

### ISSUE THREAD

**Issue by bnjbvr** [YunoHost-Apps/kresus_ynh#47]
... so weboob can use it to parse PDFs. Not sure it's actually necessary, but it's nice to have as a bonus feature.

**Comment by lenod** [comment]
I reckon this changed made my last kresus upgrade fail with:
`ERROR: Package 'pdfminer' requires a different Python: 3.5.3 not in '>=3.6'`

Indeed, python3 has version 3.5.3 on debian stretch, and yunohost doesn't support debian buster yet. Maybe consider allowing the installation of pdfminer to fail?

**Comment by Jibec** [comment]
Benjamin, what do you think?

**Comment by nicofrand** [comment]
Hi!

Just seeing this issue… I thought `pdfminer.six` was the one compatible with python3 anyway?

**Comment by bnjbvr** [comment]
Oops, yeah might be necessary to replace it by `pdfminer.six` then, sorry about this!
