### ISSUE TITLE
Update failed : pdfminer

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/kresus_ynh#49]
Pdfminer can't be installed, because Python3 is in version 3.5.3 on Stretch, but it requires >=3.6.

It breaks the update.

```
Attention : [DEBUG]: WARNING - ERROR: Package 'pdfminer' requires a different Python: 3.5.3 not in '>=3.6'
```

**Comment by lenod** [comment]
Yes, this was discussed here #47. I reckon that the fix is quite simple though.

**Comment by simon511000** [comment]
I have the same error

**Comment by lenod** [comment]
Can we disable this feature until we have a fix so that it doesn't block the updates?
