### ISSUE TITLE
Outdated weboob version

### ISSUE THREAD

**Issue by hferee** [YunoHost-Apps/kresus_ynh#52]
After upgrading to version 0.15.2., my bank accounts do not synchronise anymore.
Depending on the bank, the logs show different errors, like:
`weboob.exceptions.ModuleLoadError: cannot import name 'IsinCode'`
`ImportError: cannot import name 'TransferInvalidOTP'`

To me, it looks like weboob is outdated. The installed version is 1.6, although the latest release is 2.0 (indeed available with pip).
However, the update interface indicates that weboob is up to date.

**Comment by Jibec** [comment]
Thanks for sharing this.
What make you feel like this is related to the upgrade and not just unlikely timing. Did it work the day before the upgrade?
Logs says the bank module has an issue. Not sure I can do much for now.

**Comment by hferee** [comment]
I didn't check the day before the upgrade, but a few days before, yes.
The thing is two different banks (at least) are affected, so it's quite unlikely that it is simply a module issue. Do you know why weboob is not updated to the latest version?

**Comment by hferee** [comment]
Upgrading weboob manually indeed fixes it:
```
source "/var/www/kresus/venv/bin/activate"
pip install --upgrade weboob
```

**Comment by Jibec** [comment]
Perfect, it's what I need :)
Either I forgot to update pip modules on upgrade, or timing was bad.

**Comment by nicofrand** [comment]
Issue seems fixed, I'll close the ticket.
Please reopen an issue if needed.
