### ISSUE TITLE
Install doesn't work on 32bit

### ISSUE THREAD

**Issue by strasbourgcurieux** [YunoHost-Apps/kresus_ynh#53]
Bonjour

Le message
"Could not install kresus: An error occurred inside the app installation script"

Les log
https://paste.yunohost.org/raw/uxemapugeh

Cordialement

**Comment by bnjbvr** [comment]
Bonjour ! L'erreur finale est causée par Moulinette, probablement parce que quelque chose s'est mal passé avant :

```

2020-03-31 23:55:20,795: ERROR - Could not install kresus: An error occurred inside the app installation script
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 301, in wrapper
    curr_v = params[k]
KeyError: 'label'
```

(Mon analyse s'arrête là ; j'avais besoin de savoir si c'est un souci côté Kresus ou Yunohost, et c'est visiblement côté YNH. Bonne chance !)

**Comment by nicofrand** [comment]
Bonjour,

je tablerais sur une erreur d'installation de nodejs:

```
2020-03-31 23:55:18,408: DEBUG - + test -x /usr/bin/npm_n
2020-03-31 23:55:18,409: DEBUG - ++ uname -m
2020-03-31 23:55:18,410: DEBUG - + uname=i686
2020-03-31 23:55:18,412: DEBUG - + [[ i686 =~ aarch64 ]]
2020-03-31 23:55:18,413: DEBUG - + [[ i686 =~ arm64 ]]
2020-03-31 23:55:18,414: DEBUG - + n 10
2020-03-31 23:55:19,017: DEBUG - 
2020-03-31 23:55:19,019: DEBUG -   [36m   install[0m : [2mnode-v10.19.0[22m[0m
2020-03-31 23:55:20,125: DEBUG - 
2020-03-31 23:55:20,127: DEBUG -   [31mError: invalid version '10.19.0'[0m
2020-03-31 23:55:20,128: DEBUG - 
2020-03-31 23:55:20,131: DEBUG - + ynh_exit_properly
```

**Comment by Jibec** [comment]
Je crois que l'architecture est i686, ce qui veut dire 32bits.
Je ne sais pas si on prend vraiment en charge cette architecture. En 
tout cas, je ne l'ai jamais vraiment testé.

Je vois que pour une architecture arm, il faut passer un paramètre 
supplémentaire: 
https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/helpers.d/nodejs#L106

Quel est ton degré de maîtrise de ssh ?
Saurais-tu cloner le dépôt git, y ajouter quelques lignes à la fin du 
fichier 
https://github.com/YunoHost-Apps/kresus_ynh/blob/master/scripts/_common.sh 
?
Puis envoyer l'ensemble de l'arborescence sur ton serveur et installer 
via `yunogost app install ./kresus_ynh/` ?

**Comment by strasbourgcurieux** [comment]
Pour ma part pas du tout à l'aise avec la manipulation de dépos.
Pour instant je test installation des applications et fais le retours des messages d'erreurs.
Dans quelques semaines je fais mes premieres déposes de scripts maison.
Je reviendrais ici a ce moment là.

 "686, ce qui veut dire 32bits."
A l'heure de mes tests.
Les applications php sont toutes ok
Pour les autres langages ça dépend (ais ?) de l'application source.

A+

**Comment by Jibec** [comment]
D'accord, alors je peux te faciliter la vie pour que tu n'aies pas à 
trop apprendre d'un coup, peux-tu apprendre à te connecter à ton serveur 
en SSH ?
https://yunohost.org/#/ssh

Une fois fait, je te ferai un guide des commandes à lancer pour t'éviter 
les galères.

**Comment by nicofrand** [comment]
Node a arrêté de fournir des builds Linux pour 32 bits à partir de la version 10 : https://github.com/nodejs/build/issues/885.

**Comment by Jibec** [comment]
Le 2020-04-01 21:30, Nicolas Frandeboeuf a écrit :
> Node a arrêté de fournir des builds Linux pour 32 bits à partir de
> la version 10 : nodejs/build#885 [1].

Ok, alors c'est sans espoir de correction dans YunoHost, désolé.
Je vais faire une détection pour mettre un message d'erreur 
compréhensible pour l'utilisateur.

**Comment by alexAubin** [comment]
(I guess there's not much to do apart from possibly adding a note in the app README for now..)

**Comment by alexAubin** [comment]
Ooooor actually we could add a check like in wekan:

https://github.com/YunoHost-Apps/wekan_ynh/blob/master/scripts/install#L42

To at least avoid going so far in the install process and miserably crashing because of nodejs

**Comment by Jibec** [comment]
done in 0.16
