### ISSUE TITLE
multiple operations reverted

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/kresus_ynh#55]
few days ago, suddenly, some operations has been reverted, meaning that paying is nullified by another operation. Of course, it is not really the case.
v0.15.2~ynh4
Weboob v2.0
![kresus](https://user-images.githubusercontent.com/1232047/79923931-e5662b00-8436-11ea-8b13-64ffdf36158d.png)

**Comment by nicofrand** [comment]
Hi!

your bank's website changed the way the display negative transactions.
Weboob **core** has been patched to be able to deal with it, you need to update it.
See https://github.com/YunoHost-Apps/kresus_ynh/issues/52#issuecomment-591654887.

**Comment by klorydryk** [comment]
Weboob version is 2.0, and no update seems to be available. But ok, let's wait.

**Comment by nicofrand** [comment]
The version number is not updated as there is no minor version for weboob.
You don't need to wait, see #52 how to update weboob.

**Comment by klorydryk** [comment]
Everything seems to be already up to date. Perharps a new version has been installed, and future operations will be ok? I should remove the incorrect operations by hand thougt?

`Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: weboob in /var/www/kresus/venv/lib/python3.5/site-packages (2.0)
Requirement already satisfied, skipping upgrade: cssselect in /var/www/kresus/venv/lib/python3.5/site-packages (from weboob) (1.1.0)
Requirement already satisfied, skipping upgrade: PyYAML in /var/www/kresus/venv/lib/python3.5/site-packages (from weboob) (5.3)
Requirement already satisfied, skipping upgrade: Pillow in /usr/lib/python3/dist-packages (from weboob) (4.0.0)
Requirement already satisfied, skipping upgrade: lxml in /usr/lib/python3/dist-packages (from weboob) (3.7.1)
Requirement already satisfied, skipping upgrade: Babel in /var/www/kresus/venv/lib/python3.5/site-packages (from weboob) (2.8.0)
Requirement already satisfied, skipping upgrade: unidecode in /var/www/kresus/venv/lib/python3.5/site-packages (from weboob) (1.1.1)
Requirement already satisfied, skipping upgrade: html2text>=3.200 in /var/www/kresus/venv/lib/python3.5/site-packages (from weboob) (2020.1.16)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from weboob) (1.10.0)
Requirement already satisfied, skipping upgrade: requests>=2.0.0 in /usr/lib/python3/dist-packages (from weboob) (2.12.4)
Requirement already satisfied, skipping upgrade: python-dateutil in /usr/lib/python3/dist-packages (from weboob) (2.5.3)
Requirement already satisfied, skipping upgrade: pytz>=2015.7 in /usr/lib/python3/dist-packages (from Babel->weboob) (2016.7)
`

**Comment by nicofrand** [comment]
Yes incorrect transactions will have to be removed manually.
Maybe the pip repo is notuptodate, I'll ask.

**Comment by nicofrand** [comment]
My bad, for 2.0 the changes are actually backported in the module, not in the core.
Could you launch an update of the modules and try again?

PS: I expect your bank begins with a "B" and ends with a "A" (since that was the one where the change was spotted)?

**Comment by klorydryk** [comment]
Yes it is ;)
How do I update modules? XD

**Comment by nicofrand** [comment]
You can do it from inside Kresus in "Weboob management" : there is a button to click, "Launch the update" or something.

**Comment by klorydryk** [comment]
Oh yes, it is the first thing I did :)
