### ISSUE TITLE
Improve user experience after an upgrade

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/kresus_ynh#60]
After resolving #57 (thanks ! :+1: ), Kresus upgrade is successful, but some things are confusing, as it can be seen in this topic : https://forum.yunohost.org/t/maj-kresus-kresus-update/11164/2

* The mail sent at the end of the update has the subject "kresus was just installed". 
In the email body, it's however mentioned that "Kresus was updated!", but just after there is a message about beahvior of YNH when installing a new app.
I suppose that the same template is used when installing or upgrading, but this is disturbing, even more with the behavior of the app described below. 
**Would it be possible to have a two distinct email contents, regarding install and upgrade case?**

* After upgrading, when accessing to Kresus the first time, the "welcome page" is displayed (#/onboarding/) : https://framapic.org/n0llowULbqN1/DPkdAtZMhuQy.png
Which leads us to believe that Kresus has been in fact reinstalled and that the data may be lost.
After a click on "Administration", I arrived on the Kresus interface with all my data... ouf :sweat_smile: 
**Would it be possible to not display this page after an upgrade?**

**Comment by nicofrand** [comment]
Hi,

I'll remove the post-install part from the message, thanks. 

For the second point it is probably that you checked the app before the data migration ended (ie.. the webserver was ready but the migration was not finished yet). This should not happen anymore and is related to Kresus, not this package.

**Comment by SiM** [comment]
Hi,

I just upgraded Kresus (worked fine, thx!), but I noticed that the subject of the email is still "_Kresus was just installed_".

Would it be possible to replace _installed_ by _upgraded_ when an upgrade is done?

**Comment by nicofrand** [comment]
Hi,

this comes from a common helper (https://github.com/YunoHost-Apps/kresus_ynh/blob/bd8712156e7a78a983a3b323d7323979476e7420/scripts/_common.sh#L41), not specific to Kresus, and honestly would prefer not to touch it.

I'll see with the YunoHost team if they can provide a more generic helper to improve it.

**Comment by SiM** [comment]
Oh, I see. Thank you!
