### ISSUE TITLE
send_readme_to_admin : wrong choice

### ISSUE THREAD

**Issue by flera** [YunoHost-Apps/kresus_ynh#68]
Bonjour,
Après l'upgrade de kresus 0.16.0.ynh2.xxx en 0.16.0.ynh2.xxx (je ne me souviens pas de la valeur apres le ynh2 qui a changée), les logs affiche le message suivant : 

![image](https://user-images.githubusercontent.com/1839219/81001110-8b5a6200-8e47-11ea-8b8e-ca41e325dca5.png)

Il s'agit du fichier _common.sh ligne 52.

Est ce qu'il faudrait corriger 
$(yunohost diagnosis show | grep -B 100 "services:" | sed '/services:/d')"
en 
$(yunohost **tools** diagnosis show | grep -B 100 "services:" | sed '/services:/d')"

De plus, le retour de cette commande ne semble pas utilisé.

**Comment by nicofrand** [comment]
Salut,

le problème est qu'à partir de YunoHost 3.8 ce sera bien `yunohost diagnosis show`. Il faut donc soit attendre la 3.8 soit avoir une commande qui fonctionne selon la version.

Le retour de cette commande est directement inséré dans l'email envoyé.

**Comment by nicofrand** [comment]
Le résultat de cette commande a également changé, je vais plutôt étudier si c'est réellement utile dans l'email. Voire si l'email lui-même est réellement utile.

**Comment by flera** [comment]
Les logs de l'upgrade sont bien maintenant après les différents commit fait.

Merci
