### ISSUE TITLE
Please install Weboob 2.0 or later

### ISSUE THREAD

**Issue by ashemsay** [YunoHost-Apps/kresus_ynh#72]
Hello,
I updated my kresus app this night and when trying to access it this morning I get this message:

```
Please install Weboob 2.0 or later
In order to work as expected, Kresus has a single dependency called Weboob. Kresus could not detect a working install of Weboob (Weboob or one of its dependencies is not installed correctly). To offer you the best experience, the latest stable version of Weboob has to be installed (2.0 or later, at this point). Please contact your Kresus administrator so that they'll install Weboob as described in the README file: README 
```

I updated the weboob version:

```
source "/var/www/kresus/venv/bin/activate"
pip install --upgrade weboob
```
I restarted the kresus service

But still does not work.
Do you know what I am missing?

EDIT: I checked the logs in `/var/www/kresus/data/kresus.log` and saw this

```
ImportError: No module named 'dateutil'
```
So I installed the dateutil module:
```
source "/var/www/kresus/venv/bin/activate"
pip install python-dateutil
```
And all started working again. So I guess there is an issue with the package not installing the python-dateutil requirement.

**Comment by nicofrand** [comment]
Hi!

Thanks for the report. I am not aware of any dependency requirement of this type.
I probably should be in weboob's requirements.

Could you provide more logs to see when this happened and what code threw the error please?

**Comment by ashemsay** [comment]
Here is the log: https://coupou.fr/bin/?ded88cb2e00198d4#FQswefvjMMpthLCX1cGPbLZrRAyJjZgpJek5s71BoKKz

**Comment by nicofrand** [comment]
Could you give me the result of `pip show weboob` please (in the virtualenv)?

**Comment by nicofrand** [comment]
Can you also provide the upgrade logs please?

**Comment by ashemsay** [comment]
Here's the requested content:

```
(venv) root@domain:~# pip show weboob
Name: weboob
Version: 2.0
Summary: Weboob, Web Outside Of Browsers
Home-page: https://weboob.org/
Author: Romain Bignon
Author-email: weboob@weboob.org
License: GNU LGPL 3
Location: /var/www/kresus/venv/lib/python3.5/site-packages
Requires: lxml, unidecode, PyYAML, requests, six, Babel, Pillow, html2text, cssselect, python-dateutil
Required-by:
```

The upgrade log: https://coupou.fr/bin/?2089b51f2b0f4216#8rkvf1X4LdDH3U5jJVDw1euzkMDX5nzr1NviaLv6HSQ

**Comment by nicofrand** [comment]
Thanks.

```
2020-05-26 04:35:52,007: DEBUG - Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from weboob) (2.5.3)
```

So, it should have been there :confused:.
My guess is that it was available system-wide so it did not install it locally in the venv and then it was remove system-wide…

**Comment by ashemsay** [comment]
The thing is I did a system upgrade yesterday and I did receive my daily report at 3:14 this morning so everything was working fine (at least the sync and the email part, but I guess the account sync would need weboob to work, wouldn't it?) before the app upgrade which I had planned at 4:30 so I definitely think the upgrade broke something.

Nevermind, if there are no other cases I guess we can get on with our lives :)

Anyway thanks for looking into it.

**Comment by nicofrand** [comment]
While upgrading the current virtualenv is erased, and a new one is created.
And while creating it, pip saw that you already had this module installed so it did not re-install it. But then it was missing either because of an access right to the global installation or because of it was uninstalled from the global path.

I might have to use `--ignore-installed` (https://github.com/pypa/pip/issues/333) to force the installation in the virtualenv.

**Comment by nicofrand** [comment]
Could you run `pip list --format columns` outside of the virtualenv please?
That'll help me better understand what might have happened and prevent any further issue.

Thanks!

**Comment by ashemsay** [comment]
```
Package           Version
----------------- -------
argcomplete       1.8.1
bottle            0.12.13
chardet           2.3.0
cryptography      1.7.1
dnspython         1.15.0
enum34            1.1.6
gevent            1.1.2
gevent-websocket  0.9.3
greenlet          0.4.11
idna              2.2
ipaddress         1.0.17
Jinja2            2.8
keyring           10.1
keyrings.alt      1.3
MarkupSafe        0.23
miniupnpc         1.9
Moulinette        2.0.0
packaging         16.8
pbr               1.10.0
pip               9.0.1
psutil            5.0.1
publicsuffix      1.1.0
pyasn1            0.1.9
pycrypto          2.6.1
pygobject         3.22.0
pyOpenSSL         16.2.0
pyparsing         2.1.10
python-apt        1.4.1
python-ldap       2.4.28
pytz              2016.7
pyxdg             0.25
PyYAML            3.12
requests          2.12.4
SecretStorage     2.3.1
setuptools        33.1.1
six               1.10.0
stevedore         1.17.1
toml              0.10.0
urllib3           1.19.1
virtualenv        15.1.0
virtualenv-clone  0.2.5
virtualenvwrapper 4.3.1
wheel             0.29.0
```
