### ISSUE TITLE
Weboob error following upgrade Yunohost to v4/Buster

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/kresus_ynh#79]
I applied the migration to Buster, and it worked. But now I have an error using Kresus webpage:
_"Veuillez installer Weboob en version 2.0 ou supérieure"_

And by command line:
_sudo /var/www/kresus/venv/bin/weboob-config update_
the result is:
_Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Current thread 0x00007fadf71f9740 (most recent call first):
Abandon_

Do you know the reason and how to solve it? Thanks!

**Comment by nicofrand** [comment]
Hi!

Can you give me the result of `ls -la /var/www/kresus/venv/` please?
I don't know what happens during a YunoHost migration.

I guess reinstalling the app or upgrading it would fix it (it will recreate the venv).

**Comment by nicofrand** [comment]
Ok that's a known issue from Yunohost, there is currently nothing to do from the app's side.
They're working on it.

Meanwhile an app upgrade should fix it.

**Comment by klorydryk** [comment]
you mean like
```
sudo yunohost app upgrade kresus
Info : Mise à jour de l’application kresus …
Succès ! kresus est déjà à jour
Succès ! Mise à jour terminée
```

Not fixed with it :s

**Comment by nicofrand** [comment]
You have to force the upgrade: `YNH_FORCE_UPGRADE sudo yunohost app upgrade kresus`

**Comment by klorydryk** [comment]
Same result with
`sudo YNH_FORCE_UPGRADE=1 yunohost app upgrade kresus`
:(

**Comment by nicofrand** [comment]
Can you give the result of the command please?

**Comment by klorydryk** [comment]
Same:
_~$ sudo YNH_FORCE_UPGRADE=1 yunohost app upgrade kresus
Info : Mise à jour de l’application kresus …
Succès ! kresus est déjà à jour
Succès ! Mise à jour terminée_

**Comment by nicofrand** [comment]
Tu peux essayer avec `sudo yunohost app upgrade kresus -u https://github.com/YunoHost-Apps/kresus_ynh` alors ?

**Comment by klorydryk** [comment]
Trop bien, ça a fonctionné !
Merci.
