### ISSUE TITLE
Can't updgrade Kresus

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/kresus_ynh#93]
Here is the log pastebin : https://paste.yunohost.org/raw/radomifeko

I'm going to try installing the jpeg library.

**Comment by nicofrand** [comment]
Hi,

thanks for reporting. That's weird, I would expect `python3-pillow` to define it in its dependencies: https://packages.debian.org/fr/source/buster/pillow

**Comment by Salamandar** [comment]
Hi,
I tried upgrading, that worked, but I lost all my data (i'm at the onboarding page). Do you know where the old data may be ? The databases in /home/yunohost.backup look too small (300kB).

**Comment by nicofrand** [comment]
Hi,

do you have the logs please?
