### ISSUE TITLE
upgrade to v0.17 📦

### ISSUE THREAD

**Issue by bnjbvr** [YunoHost-Apps/kresus_ynh#95]
In particular, some attention is required to rename "weboob" in "woob" in all the environment variables and `config.ini` options.

**Comment by bnjbvr** [comment]
Also should use the new woob's repo, located at https://gitlab.com/woob/woob/

**Comment by nicofrand** [comment]
Fixed in 8527c5d0a9561025f3d724166afdcaf2be68f278
